version: '3'
services:
  bifrost:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: unless-stopped
    container_name: bifrost
    volumes:
      - "./pair_data:/pair_data"
    ports:
      - 9999:9999