channels:
- conda-forge
dependencies:
- python=3.8.10
- pip
- pip:
  - flask
  - pandas
  - flask_restx
  - python-dateutil
  - setuptools
  - wheel
  - pytest
  - pytest-cov
  - flake8
  - flake8-html
  - mypy
  - xgboost
  - numpy
  - sklearn
  - graphviz
name: container-environment