# Hosting
HOST_IP_RANGE = '0.0.0.0'
HOST_PORT = 9999

# Application
APP_NAME = 'Bifröst'
APP_DESCRIPTION = 'FrostAura Bifröst is a platform for making forecasts, predictions and decisions.'
APP_VERSION = '1.0.0'
APP_ROUTE_PREFIX = 'api/v1'

# Caching
MODEL_CACHE_AGE_IN_HOURS = 6
MODEL_CACHE_IN_SECONDS = MODEL_CACHE_AGE_IN_HOURS * 60
MODEL_BULK_INFERENCE_CACHE_IN_HOURS = 1
MODEL_BULK_INFERENCE_CACHE_IN_SECONDS = MODEL_BULK_INFERENCE_CACHE_IN_HOURS * 60
